### PR TITLE
Warn on a long pattern in top-level lambda

### PR DESCRIPTION
**Pull request by viraptor**
When there are more than 6 arguments, suggest splitting into multiple lines.

### CODE REVIEW

**Comment by nerdypepper** [comment]
i would say this is a formatting preference, and should be handled by formatting tools, rather than a linter, cc'ing some contributors for their opinions

cc @antifuchs @chenrui333 @NobbZ

**Comment by NobbZ** [comment]
Yeah, for me this is clearly in the domain of a formatter.

**Comment by viraptor** [comment]
So my idea behind putting it in a linter is that there are two aspects to this issue:

- formatter: this is the policy how it should be formatted, it's enforced
- linter: this specific case is long and not readable anymore, but it's up to you how you fix it

**Comment by SuperSandro2000** [comment]
> i would say this is a formatting preference, and should be handled by formatting tools, rather than a linter, cc'ing some contributors for their opinions

Yeah, I don't think that is fitting, too.

**Comment by ilkecan** [comment]
The number of arguments should be configurable rather than hardcoding 6, if this is accepted.

**Comment by nerdypepper** [comment]
while i do appreciate the work gone into this PR, i don't think this patchset fits in statix. i am very sorry, but i am going to have to close this one. i am very glad to have your contributions in statix however @viraptor!

**Pull request closed without merging**
